# services:
#   api:
#     build:
#       dockerfile: ./code/deployment/api/Dockerfile
#       context: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./models:/app/models

#   app:
#     build:
#       dockerfile: ./code/deployment/app/Dockerfile
#       context: .
#     ports:
#       - "8501:8501"
#     environment:
#       - API_URL=http://api:8000


services:
  api: 
    build: 
      dockerfile: ./code/deployment/api/Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      MODEL_DIR: /models
    volumes:
    - ./models:/models   
    networks:
      - net

  app: 
    build: 
      dockerfile: ./code/deployment/app/Dockerfile
      context: .
    ports:
      - "3000:8501"
    environment:
      BACKEND_URL: http://api:8000
    networks:
      - net

networks:
  net:
    driver: bridge  