services:
  api:
    build:
      context: ../..
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "8000:8000"

  app:
    build:
      context: ../..
      dockerfile: code/deployment/app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api